# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b26a920b340d093a98086bfc782847a8dfe4afc60da3d2d100d849f74a01346b4a1eb8e94bd7c44dc58a0c0bb81924bf42408b464bcba6b57322ebd791752b2

test:
  secret_key_base: 0fff87926a23af8f232088152bab932b3f3a669004ca7b8c30c6669b10c274d68cad83f16cb2f2a62b3ed28d83034235eea52afc25b6656115154e9c35d19880

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ENV['SECRET_KEY_BASE']
